#!/bin/bash
git fetch upstream && \
    git checkout stable/2.2.x && git merge --ff-only upstream/stable/2.2.x && \
    git checkout stable/2.1.x && git merge --ff-only upstream/stable/2.1.x && \
    git checkout stable/1.11.x && git merge --ff-only upstream/stable/1.11.x && \
    git checkout master && git merge --ff-only upstream/master
