#!/bin/bash
git fetch upstream && \
    # git checkout stable/4.2.x && git merge --ff-only upstream/stable/4.2.x && \
    git checkout stable/4.1.x && git merge --ff-only upstream/stable/4.1.x && \
    git checkout stable/3.2.x && git merge --ff-only upstream/stable/3.2.x && \
    git checkout main && git merge --ff-only upstream/main
