#!/bin/bash
git fetch upstream && \
    git checkout stable/1.6.x && git merge --ff-only upstream/stable/1.6.x && \
    git checkout stable/1.5.x && git merge --ff-only upstream/stable/1.5.x && \
    git checkout master && git merge --ff-only upstream/master
